/* ============================================================
 * 碧樹圏のマップ(第1章)
 *   ハナゾノ ─東─ 苔むす獣道 ─東─ 花粉の湿地 ─東─ 守護獣の森殿
 *      └南─ 倒木の旧街道 ─北─┘(獣道の南)
 *   旧街道の西端の倒木をヒノコが焼くと、ハナゾノへの近道になる。
 *   マップの文字は tools なしで直せるように、そのまま置いている(凡例は types.ts)。
 * ============================================================ */
import type { MapDef, MapId } from './types.ts';

const ROWS_HANAZONO = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TT.....,T"..TTT..T....TT.TTTT.,...TT',
  'TT..xxxxx..............,..xxxxx...TT',
  'TT,.xxxxx.................xxxxx..TTT',
  'TT..xxxxx...============..xxxxx...TT',
  'TT....:.....============....:..,..TT',
  'TTT...:..,..===xxxxxx===....:....TTT',
  'TTT...:.....===xxxxxx===....:....TTT',
  'TT,...:::::::==xxxxxx===::::......TT',
  'TT..........===xxxxxx===::::::::.:::',
  'TT..........============...:::::::::',
  'TTT.........============:::,...:::::',
  'TT..........============...::.....TT',
  'TT.......bbb....:::.........:.....TT',
  'TTT~~~~~.......":::......"..:.....TT',
  'TT.~WWW~.,....".:::.....".xxxxx..TTT',
  'TTT~WWW~:::::::::::.,.,.."xxxxx..TTT',
  'TT.~~~~~.......,:::.......xxxxx...TT',
  'TTT.,...........:::....,......,bbTTT',
  'TTT..........,..:::......,.,..,..TTT',
  'TT.T..T.T.T.TT..:::.."T.TT.TTTT.T.TT',
  'TTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTT',
];

const ROWS_TRAIL = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTT.mmmmmmmmmmmmTT.m..TT"T..T.T...TRTT.T.TTT',
  'TT.TT.m,,,......,mTT....b"m..m....m.""b...."TT',
  'TT.TT.m,,,,,,,,,,mTT,..mb.,bm..".m..mTTTT...TT',
  'TT.TT.mmmmmmmmmmmmTTmm..m.mR..m..mm..TTTTm.mTT',
  'TTTTTTTTTTTT::TTTTTTm.."......m.,...bTTTT...TT',
  'TT.,,...b.R.::.......b."...."."b....mTTTT..TTT',
  'TT..TTTT.m..::.........R.......m.m.....mm.m"TT',
  'TT..TTTT,.m.::...m......m.:::::.....,.."....TT',
  'TT..TTTT.m..::..m"m..:::::::::::.........".mTT',
  'TT..."......::b....m:::::::R.m:::..b..m.....TT',
  'TTT.b.......::.m....::R####R..m::"...,.".".TTT',
  ':::.......m.::.....:::R####R...:::...."..m.:::',
  '::::::::::::::::m..::.R####R"..b::::::::::::::',
  ':::::::::::::::::::::.R####R"m...:::::::::::::',
  'TTT.""..R.m."..:::::.RRRRRRR....:::..m...b."TT',
  'TT,.b,,...........:::R.........:::"...mm....TT',
  'TTT,.TTTTTm."b.....:::.,m.....:::.....m.,."TTT',
  'TTT..TTTTT.m....."..::::::::::::m..TTTTT..".TT',
  'TTT..TTTTT....,m.m.".::::::::::.m..TTTTT...mTT',
  'TTT..TTTTT....TTTTTT..."..::.......TTTTT...TTT',
  'TTT.........".TTTTTT..m...::..m....TTTTTm..mTT',
  'TTR......m..".TTTTTT..m.b.::...TTTTTTTTT..m.TT',
  'TTm.......b...TTTTTT......::.m"TTTTm...m....TT',
  'TT..m.................m.".::...TTTTm.".."..mTT',
  'TT..........m".....m....m.::...TTTT,"..b....TT',
  'TT.m.".T.TTm...TTT.TTTmm.:::..TT...m.m.T.T.TTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTTT',
];

const ROWS_ROAD = [
  'TTTTTTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTT:::TTTTTTTTTTTTTTTTTTTTT',
  'TTTT..TTT,T""T....TT:::T..TTTTTT.T..T...T.TT',
  'TT..TTTTTT.........".::....TTTTT......"..TTT',
  'TT..TTTTTT.,.........::....TTTTT.R.......TTT',
  'TTT.TTTTTT...........::"........"..".....TTT',
  'TTT.TTTTTT.".........::."....::::::::::::.TT',
  'TT..TTTTTT......"...b::b.....:..........:.TT',
  'TT.....RT......R.....::..b.".:.::::xxx:.:.TT',
  'TT......T.......,..::::.....R:.::::xxx:.:.TT',
  'TTT....bT...."R..:::::.......:.::::::::.:TTT',
  ':::..........b.:::::.""......:.::::::::.:.TT',
  '::::::::::::::::::::::::::::::.::::::::.:TTT',
  '::::::::::::::::::::::::::::::.:xx:::::.:.TT',
  'TT.:::::::::::::::::::::::::::.:xx:::::.:bTT',
  'TTTTTTTTT.....,..............:.::::::::.:.TT',
  'TTTTTTTTT."............".....:..........:RTT',
  'TTTTTTTTT.TTTTTTT.....TTTTT..::::::::::::TTT',
  'TTTTTTTTT.TTTTTTT.....TTTTT..b.....,......TT',
  'TTTTTTTTTTTTTTTTT...".TTTTT...............TT',
  'TTTTTTTTTTTTTTTTT.....TTTTT...........".RTTT',
  'TTTTTTTTTTTTTTTTT...."TTTTT,.R..".........TT',
  'TTTTTTTTTT............TTTTT..""..........TTT',
  'TTTTTTTTTT..TTT....T..TT.TTTT.T.TT.TT...."TT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];

const ROWS_MARSH = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TT.TT...........TT.TTTTTT..T..T.T...TT..T.TT',
  'TT.pppppppprppp.p.prTTpTTpp..ppppppppppppTTT',
  'TTTppppppppppppppppppppppppppppppppppppp..TT',
  'TT.pppppppppppppppppppppppppppppppppppppp.TT',
  'TT.ppTpp~~o~~o~~~~~~~~~~~~~~~~o~~~~~ppppp.TT',
  'TTTppppp~~~~~~~~~~~~~~~~~~~~~~~~~o~~pppppTTT',
  'TT..pppp~~~~WWWWWWWWWWWWWWWWWWWW~~~~ppppp.TT',
  'TT.p.ppp~~~~WWWWWWWWWWWWWWWWWWWW~~~~ppppr.TT',
  'TT..pppp~~~~WWWWWWWWWWWWWWWWWWWW~~~~ppppp.TT',
  ':::TTrpp~~~~WWWWWWWWWWWWWWWWWWWW~~~~prppp:::',
  '::pppTpp~~~~WWWWWWWWWWWWWWWWWWWW~~~~p.ppp:::',
  '::ppppTp~~~~WWWWWWWWWWWWWWWWWWWW~~~~rpppp:::',
  'TT.p.ppp~~~~WWWWWWWWWWWWWWWWWWWW~~~~pppp..TT',
  'TTTpTrp.~~~~WWWWWWWWWWWWWWWWWWWW~~~~pppTr.TT',
  'TTTpp..p~~~~WWWWWWWWWWWWWWWWWWWW~~~~.pppT.TT',
  'TT.pprpp~~~~~~~~~~......~~~~~~~~~~~~Tr.rp.TT',
  'TT.ppp.p~o~~~~~~~~.,,,,.~~~~~~~~~~o~.Tp.p.TT',
  'TT.T.Tpp~~~~~~~~~~.,,,,.~~~~~~~~~~~~TTTpp.TT',
  'TTTppppp~~~~~~~~~~......~~~~~~~~~~~~Tpppp.TT',
  'TT.TpTppppppppppp~~~~~~~~TTTTTTTTTTTTpTpT.TT',
  'TT.ppppppppppppppppppppppTTTTTTTTTTTTpppp.TT',
  'TT.TT.T.T.....TTTT.TT.TTT.T........T.....TTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
];

const ROWS_SHRINE = [
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
  'TTTTmT.T...xxxxxxxx..TT..T.TTT',
  'TTT".mm....xxxxxxxx.mm.....TTT',
  'TTT....mm..xxxxxxxx....m..mTTT',
  'TTTT...m...xxxxxxxx........TTT',
  'TTT...m....xxxxxxxx...m....TTT',
  'TTT....ssssssssssssssss.m..TTT',
  'TTT.m..ssssssssssssssss..m.TTT',
  'TTTm.m.ssRssssssssssRss....TTT',
  'TTTmmm.ssssssssssssssss...TTTT',
  'TTTm~~~ssssssssssssssss~~~.TTT',
  'TTTT~~~ssRssssssssssRss~~~.TTT',
  'TTT"~~~ssssssssssssssss~~~TTTT',
  'TTT.~~~ssssssssssssssss~~~TTTT',
  'TTT.~~~ssRssssssssssRss~~~.TTT',
  'TTTT~~~ssssssssssssssss~~~.TTT',
  'TTT....ssssssssssssssssm..TTTT',
  'TTTmm.mssRssssssssssRss....TTT',
  'TTT..".ssssssssssssssss....TTT',
  'TTT...m......ssssm........"TTT',
  'TTT.".m......ssss..."......TTT',
  'TTT......".m.ssss...m..m...TTT',
  'TTT....m.m..mssss".m.m".m..TTT',
  'TTTm.m.mm....ssss..........TTT',
  'TTTT.m.......ssss....mm....TTT',
  'TTTTm........ssss..m.mmmm..TTT',
  'TTT.."......mssss.."m"m.m..TTT',
  'TTT...mm...."ssss......m..TTTT',
  'TTT"mT.T.....ssss...T..Tmm.TTT',
  'TTTTTTTTTTTTTssssTTTTTTTTTTTTT',
  'TTTTTTTTTTTTT::::TTTTTTTTTTTTT',
  'TTTTTTTTTTTTT::::TTTTTTTTTTTTT',
];

const hanazono: MapDef = {
  id: 'hanazono', name: '樹上集落ハナゾノ', theme: 'village', bgm: 'village', rows: ROWS_HANAZONO,
  points: {
    start: [6.5, 8.5], lab: [6.5, 8.5], spring: [9.5, 16.5], east_gate: [33.5, 11.5], south_gate: [17.5, 21.5],
  },
  objects: [
    { id: 'lab', kind: 'prop', prop: 'lab', x: 6.5, y: 6, solid: false },
    { id: 'great_tree', kind: 'prop', prop: 'great_tree', x: 18, y: 11, solid: false },
    { id: 'house_ne', kind: 'prop', prop: 'house', x: 28.5, y: 6, solid: false },
    { id: 'house_se', kind: 'prop', prop: 'house', x: 28.5, y: 19, solid: false },
    { id: 'lantern_1', kind: 'prop', prop: 'lantern', x: 12.5, y: 5.6, solid: false },
    { id: 'lantern_2', kind: 'prop', prop: 'lantern', x: 23.5, y: 5.6, solid: false },
    { id: 'lantern_3', kind: 'prop', prop: 'lantern', x: 12.5, y: 13.6, solid: false },
    { id: 'lantern_4', kind: 'prop', prop: 'lantern', x: 23.5, y: 13.6, solid: false },
    { id: 'beehive_1', kind: 'prop', prop: 'beehive', x: 30.5, y: 19.8 },
    { id: 'beehive_2', kind: 'prop', prop: 'beehive', x: 33.5, y: 20.8 },
    { id: 'spring', kind: 'spring', prop: 'spring', x: 8.5, y: 16.8 },
    { id: 'record_village', kind: 'record', prop: 'record_stone', x: 11.5, y: 15.8 },
    { id: 'sign_village', kind: 'sign', prop: 'sign', x: 31.5, y: 13.8, talk: 'sign_village' },
    { id: 'kaede', kind: 'npc', art: 'kaede', x: 8.5, y: 8.3, face: 'right', talk: 'kaede' },
    { id: 'villager_a', kind: 'npc', art: 'villager_a', x: 32.5, y: 9.5, face: 'left', talk: 'villager_a' },
    { id: 'villager_b', kind: 'npc', art: 'villager_b', x: 25.5, y: 7.5, face: 'left', talk: 'villager_b' },
    { id: 'villager_c', kind: 'npc', art: 'villager_c', x: 11.5, y: 12.5, face: 'right', talk: 'villager_c' },
    { id: 'villager_d', kind: 'npc', art: 'villager_d', x: 29.5, y: 20.5, face: 'left', talk: 'villager_d' },
  ],
  exits: [
    { x: 35, y: 10, w: 1, h: 3, to: 'trail', point: 'west' },
    { x: 16, y: 23, w: 3, h: 1, to: 'road', point: 'west' },
  ],
  triggers: [],
  spawns: [],
  enter: { knot: 'epilogue', when: ['shrine_done', '!chapter_done'] },
};

const trail: MapDef = {
  id: 'trail', name: '苔むす獣道', theme: 'forest', bgm: 'forest', rows: ROWS_TRAIL,
  points: {
    west: [1.5, 14.5], east: [44.5, 14.5], south: [26.5, 28.5],
    fork: [19.5, 15], east_exit: [44, 14.5], south_exit: [26.5, 28],
  },
  objects: [
    { id: 'ren_trail', kind: 'npc', art: 'ren', x: 20.5, y: 15.5, face: 'left', talk: 'trail_ren', when: ['!met_ren'] },
    { id: 'sign_trail', kind: 'sign', prop: 'sign', x: 16.5, y: 12.8, talk: 'sign_trail' },
    { id: 'record_trail', kind: 'record', prop: 'record_stone', x: 17.5, y: 17.8 },
    { id: 'thorn_trail', kind: 'gate', x: 13, y: 7, gate: { kind: 'thorns', w: 2, h: 1, need: ['fire'], flag: 'thorn_trail' } },
    { id: 'grove_journal', kind: 'sign', prop: 'stump', variant: 1, x: 10.5, y: 3.8, talk: 'grove_journal' },
    { id: 'chest_grove', kind: 'chest', prop: 'chest', x: 14.5, y: 3.8, item: { id: 'revive', n: 1, flag: 'chest_grove' } },
    { id: 'mush_1', kind: 'prop', prop: 'mushroom', x: 7.5, y: 4.8, solid: false },
    { id: 'mush_2', kind: 'prop', prop: 'mushroom', x: 36.5, y: 17.8, solid: false },
  ],
  exits: [
    { x: 0, y: 13, w: 1, h: 3, to: 'hanazono', point: 'east_gate' },
    { x: 45, y: 13, w: 1, h: 3, to: 'marsh', point: 'west' },
    { x: 25, y: 29, w: 3, h: 1, to: 'road', point: 'north' },
  ],
  triggers: [
    { id: 'trg_ren', x: 15, y: 12, w: 2, h: 6, knot: 'trail_ren', when: ['!met_ren'] },
  ],
  spawns: [
    { x: 20, y: 3, w: 16, h: 4, species: ['konezumi', 'kobato', 'hanamochi'], count: 2, level: [2, 3], group: [1, 2] },
    { x: 3, y: 20, w: 11, h: 7, species: ['konezumi', 'birimushi'], count: 2, level: [2, 3], group: [1, 2] },
    { x: 34, y: 7, w: 8, h: 6, species: ['birimushi', 'hanamochi', 'kobato'], count: 2, level: [2, 3], group: [1, 2] },
  ],
  enter: { knot: 'trail_enter' },
};

const road: MapDef = {
  id: 'road', name: '倒木の旧街道', theme: 'road', bgm: 'road', rows: ROWS_ROAD,
  points: {
    north: [21.5, 1.5], west: [1.5, 12.5], camp: [30.5, 12.5], north_exit: [21.5, 1.2], log_west: [6.5, 12.5],
  },
  objects: [
    { id: 'log_road', kind: 'gate', x: 8.5, y: 15, gate: { kind: 'log', w: 1, h: 4, need: ['fire'], flag: 'log_road' } },
    { id: 'tent', kind: 'prop', prop: 'tent', x: 36.5, y: 10, solid: false },
    { id: 'ashstar_device', kind: 'prop', prop: 'device', x: 33, y: 15, solid: false },
    { id: 'crate_1', kind: 'prop', prop: 'crate', x: 38.5, y: 14.8 },
    { id: 'crate_2', kind: 'prop', prop: 'crate', x: 39.5, y: 15.8 },
    { id: 'ashstar_worker', kind: 'npc', art: 'ashstar', x: 31.5, y: 11.5, face: 'left', talk: 'ashstar_worker',
      when: ['!device_stopped|ashstar_choice=listen'] },
    { id: 'sign_road', kind: 'sign', prop: 'sign', x: 23.5, y: 9.8, talk: 'sign_road' },
    { id: 'stump_1', kind: 'prop', prop: 'stump', x: 14.5, y: 8.8 },
    { id: 'stump_2', kind: 'prop', prop: 'stump', x: 26.5, y: 15.8 },
  ],
  exits: [
    { x: 20, y: 0, w: 3, h: 1, to: 'trail', point: 'south' },
    { x: 0, y: 11, w: 1, h: 3, to: 'hanazono', point: 'south_gate' },
  ],
  triggers: [
    { id: 'trg_camp', x: 27, y: 6, w: 2, h: 12, knot: 'road_ashstar', when: ['!device_stopped'] },
  ],
  spawns: [
    { x: 10, y: 3, w: 10, h: 6, species: ['konezumi', 'kobato', 'iwakoro'], count: 2, level: [3, 4], group: [1, 2] },
    { x: 10, y: 14, w: 12, h: 8, species: ['birimushi', 'iwakoro'], count: 2, level: [3, 4], group: [1, 2] },
  ],
};

const marsh: MapDef = {
  id: 'marsh', name: '花粉の湿地', theme: 'marsh', bgm: 'marsh', rows: ROWS_MARSH,
  points: { west: [1.5, 12.5], east: [42.5, 12.5], west_exit: [1.2, 12.5], east_exit: [42.8, 12.5] },
  objects: [
    { id: 'pollen_marsh', kind: 'gate', x: 22.5, y: 6,
      gate: { kind: 'pollen', w: 1, h: 3, need: ['water', 'wood'], flag: 'pollen_marsh', when: ['device_stopped'],
        locked: '花粉が濃すぎて、水でも蔓でも歯が立たない。どこかで森の力が乱されているようだ。' } },
    { id: 'vine_marsh', kind: 'gate', x: 21, y: 22, gate: { kind: 'vine', w: 2, h: 1, need: ['wood'], flag: 'vine_marsh' } },
    { id: 'chest_islet', kind: 'chest', prop: 'chest', x: 20.5, y: 18.8, item: { id: 'potion', n: 3, flag: 'chest_islet' } },
    { id: 'sign_marsh', kind: 'sign', prop: 'sign', x: 4.5, y: 9.8, talk: 'sign_marsh' },
    { id: 'record_marsh', kind: 'record', prop: 'record_stone', x: 39.5, y: 9.8 },
    { id: 'mush_m1', kind: 'prop', prop: 'mushroom', x: 3.5, y: 17.8, solid: false },
  ],
  exits: [
    { x: 0, y: 11, w: 1, h: 3, to: 'trail', point: 'east' },
    { x: 43, y: 11, w: 1, h: 3, to: 'shrine', point: 'entrance' },
  ],
  triggers: [],
  spawns: [
    { x: 3, y: 3, w: 5, h: 18, species: ['hanamochi', 'mizuuo'], count: 2, level: [4, 5], group: [1, 2] },
    { x: 24, y: 3, w: 12, h: 3, species: ['hanamochi', 'birimushi', 'mizuuo'], count: 2, level: [4, 5], group: [1, 3] },
    { x: 36, y: 14, w: 5, h: 8, species: ['mizuuo', 'hanamochi'], count: 1, level: [4, 5], group: [2, 3] },
  ],
  enter: { knot: 'marsh_enter' },
};

const shrine: MapDef = {
  id: 'shrine', name: '守護獣の森殿', theme: 'shrine', bgm: 'shrine', rows: ROWS_SHRINE,
  points: { entrance: [15, 31.5], altar: [15, 10.5], ren_exit: [15, 32.5] },
  objects: [
    { id: 'altar', kind: 'prop', prop: 'altar', x: 15, y: 9, solid: false },
    { id: 'moridorado', kind: 'guardian', art: 'dragon', x: 15, y: 8.6, face: 'right', talk: 'shrine_enter', solid: false },
    { id: 'ren_shrine', kind: 'npc', art: 'ren', x: 12.5, y: 11.5, face: 'right', talk: 'shrine_enter', when: ['!shrine_done'] },
    { id: 'shrine_gate', kind: 'prop', prop: 'shrine_gate', x: 15, y: 27, solid: false },
    { id: 'record_shrine', kind: 'record', prop: 'record_stone', x: 18.5, y: 24.8 },
  ],
  exits: [
    { x: 13, y: 33, w: 4, h: 1, to: 'marsh', point: 'east' },
  ],
  triggers: [
    { id: 'trg_shrine', x: 7, y: 17, w: 16, h: 2, knot: 'shrine_enter', when: ['!shrine_done'] },
  ],
  spawns: [],
};

export const MAPS: Record<MapId, MapDef> = { hanazono, trail, road, marsh, shrine };
